### ISSUE TITLE
Include aggregate alias in list for ORDER BY

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#100]
**Is your feature request related to a problem? Please describe.**

When using the aggregate query builder it would be nice if we listed the alias field in the ORDER BY. Consider the following example,

![image](https://user-images.githubusercontent.com/12695796/155711006-087a16b2-81a0-48d8-8500-78828046374a.png)

The `count()` is listed but we should probably just list the alias `stars`.

This is a minor @scottlepp

**Comment by SpencerTorres** [comment]
This has been added in [v4](https://github.com/grafana/clickhouse-datasource/releases)

Instead of just the alias, it shows the full aggregate function + alias. I found that for large tables the alias is hard to find among regular columns, which is why I included the function too

![image](https://github.com/grafana/clickhouse-datasource/assets/28887171/869edaa0-fe13-4e22-88dd-d0e5db6b5496)
