### ISSUE TITLE
Add a CONTRIBUTING.md with run locally instructions

### ISSUE THREAD

**Issue by chenlujjj** [grafana/clickhouse-datasource#164]
It seems that there is no such guide in the repository.

**Comment by washcroft** [comment]
**Here's a ZIP containing a built latest version (as of now):**
https://github.com/4thu/clickhouse-datasource/raw/main/grafana-clickhouse-datasource.zip

To build your own, follow the [Grafana instructions](https://grafana.com/tutorials/build-a-data-source-backend-plugin/):

Clone/download repo

```
cd clickhouse-datasource
yarn install
yarn build
go get -u github.com/grafana/grafana-plugin-sdk-go
go mod tidy
mage -v
```

Now, rename the new dist folder grafana-clickhouse-datasource, and ZIP it up (so that the grafana-clickhouse-datasource folder is in the ZIP).

Finally, follow the [Grafana instructions](https://grafana.com/docs/grafana/latest/administration/plugin-management/) for installing a plugin from ZIP, remember to add **grafana-clickhouse-datasource** to the allowed list of unsigned plugins.

**Comment by chenlujjj** [comment]
> 

Thanks for the quick reply, I will try it out.

**Comment by gingerwizard** [comment]
@bossinc we should add a CONTRIBUTING.md with these instructions
