### ISSUE TITLE
Visualizing traces from Clickhouse

### ISSUE THREAD

**Issue by gelicia** [grafana/clickhouse-datasource#712]
### Discussed in https://github.com/grafana/grafana/discussions/62924

<div type='discussions-op-text'>

<sup>Originally posted by **mustafaakin** February  4, 2023</sup>
We're using OpenTelemetry Collector to extract the traces to Clickhouse. It's working well, we also setup some dashboards for regular SQL queries.  https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter

But I also want to visualize the traces, given a TraceId. I used the Traces panel, but no matter how many queries I tried, aliasing the columns and such, I could not find a way. Any pointers would be great. 

Should all the columns be present in the following [data type](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/trace.ts#L28), regardless of data source, or any special work must be done for each data source? </div>

**Comment by SpencerTorres** [comment]
Hey @mustafaakin

In the [data type](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/trace.ts#L28) you linked, some of the fields have a different name compared to what you used.

```diff
-SELECT TraceId                    as traceId,
+SELECT TraceId                    as traceID,
-       SpanId                     as spanId,
+       SpanId                     as spanID,
-       ParentSpanId               as parentSpanId,
+      ParentSpanId               as parentSpanID,
```

By using `ID` instead of `Id`, I was able to get the panel to appear. It appears most of the columns are optional.

Based on the panel data you shared, it appears you're using an older version of the plugin. Since you're using OpenTelemetry, I would recommend upgrading to `v4.x`, which has dedicated features for viewing traces collected by the OTEL ClickHouse exporter. See the releases [here](https://github.com/grafana/clickhouse-datasource/releases). You can also preview the SQL generated by this new version to see how it generates OTEL trace queries.

Thanks!
