### ISSUE TITLE
trace query: inspect otel_traces_trace_id_ts table to speed query by traceID

### ISSUE THREAD

**Issue by hanjm** [grafana/clickhouse-datasource#724]
**What happened**:
It is amazing cool that the new verision plugin add trace query support.

but when data amout grow, the query by traceID performance downgrade beacuse the  query sql it not inspect  `otel_traces_trace_id_ts` table.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13442#issuecomment-1235284835
> the otel_traces_trace_id_ts table is the key design, it is a small table order by traceID, write by materialized view, so it is very fast to query the start time and end time for a traceID, then query the otel_traces table by traceID with time range effectively.

query sql example: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/README.md?plain=1#L148

**What you expected to happen**:
Query by traceID inspect `otel_traces_trace_id_ts` 
**How to reproduce it (as minimally and precisely as possible)**:
Write many trace spans (more than 1 billion per day), query by traceID.
**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 10.1
- Plugin version: 4.0.0
- OS Grafana is installed on: Linux
- User OS & Browser:
- Others:

**Comment by SpencerTorres** [comment]
This is very interesting, thank you for mentioning this.

Submitted #725 to enable this for Trace ID queries with OTel. I tested it and can already see the performance improvements, even on a much smaller dataset.

However... when I go back further to older trace IDs, it no longer returns the trace data. It seems it's getting filtered out because the trace ID is no longer present in the `otel_traces_trace_id_ts` table. The trace is still there in the `otel_traces` table, so it's not like it's been deleted by a TTL.

This might need to be a separate switch on the UI for Trace ID queries.
If you're using Trace Search we could conditionally enable/disable the setting if the dashboard time is far enough back.

**Comment by SpencerTorres** [comment]
As a reminder, this is now available in [4.0.3](https://github.com/grafana/clickhouse-datasource/releases)

**Comment by hanjm** [comment]
great, Thanks.
