### ISSUE TITLE
breaking dashboards after version upgrade 3=>4

### ISSUE THREAD

**Issue by m1cha3lf** [grafana/clickhouse-datasource#730]
**What happened**:

All dashboards break after upgrading the plugin from 3 => 4

**What you expected to happen**:

Everything should stay the same or improve

**How to reproduce it (as minimally and precisely as possible)**:

I was able to break it down to the missing selector `Format` in QueryBuilder. 

In version 3 i add a new graph as timeseries and define this query
```sql
select toStartOfMinute(dt) as dt,
       count(*),
       errorcode    as code

from default.test

where (dt >= $__fromTime AND dt <= $__toTime)

group by dt, code
order by dt asc
```
In Format i select "Time Series". The graph is correctly showing a timeseries including my group-by data.

In version 4 the Format selector is missing. The time series graph is always ignoring the group-by data and only showing a wired graph with count() information.

I did check the JSON model of the dashboard and i see that it was marked as ` "queryType": "table"` .  

If i change manually the JSON model to `timeseries` it works again.

How can I make a timeseries graph with group-by work again in plugin version 4?

**Anything else we need to know?**:

Version 4:
<img width="1318" alt="Screenshot 2024-02-24 at 09 13 40" src="https://github.com/grafana/clickhouse-datasource/assets/8667579/39a6600b-f193-41b4-a91b-a4b900b4eed0">

Version 3:
<img width="1320" alt="Screenshot 2024-02-24 at 09 12 29" src="https://github.com/grafana/clickhouse-datasource/assets/8667579/b4c76a73-a634-41f2-adf5-b5bb52417e9c">

**Environment**:

- Grafana version: OSS version and Cloud behave the same
- Plugin version: 3-4
- OS Grafana is installed on:
- User OS & Browser: Firefox / Chrome Mac OSx
- Others:

**Comment by SpencerTorres** [comment]
Hello! Thank you for the issue report.

This sounds like an issue with the query migration logic from v3 to v4.

Can you share the panel/query json of the original (broken) query? Also include the fixed version if you have one.

Thanks!

**Comment by m1cha3lf** [comment]
Hi Spencer,

actually it happens on new dashboards as well. 

i have created one new dashboard with plugin version 3 and one with 4.  The results are the same as in my initial post

Attached the exported JSON

V3
[v3.json](https://github.com/grafana/clickhouse-datasource/files/14392345/v3.json)
<img width="919" alt="Screenshot 2024-02-24 at 10 37 51" src="https://github.com/grafana/clickhouse-datasource/assets/8667579/b0ab54a2-19c4-4df6-99cf-8857d7ace2b6">

V4
[v4.json](https://github.com/grafana/clickhouse-datasource/files/14392348/v4.json)
<img width="908" alt="Screenshot 2024-02-24 at 10 31 07" src="https://github.com/grafana/clickhouse-datasource/assets/8667579/662529f1-03a9-4065-bfb2-ebe57fda1c6c">


I hope that helps. Otherwise i can setup a grafana cloud instance and share access 


Thanks a lot for checking this issue!

**Comment by SpencerTorres** [comment]
So it looks like the migration script is working correctly. When updating v4 all of my testing showed that there was no change to the panel data within dashboard view when editing the `format`.

This query proved me wrong. Even though the panel type can be manually selected, the `format` value does have an effect on how the data is presented.

To fix this, I have re-enabled the `queryType`/`format` selector in dashboard view so that you can select the preferred data format. This will show the data as it is in your v3 screenshot.

Thank you for submitting this issue, hopefully we can get this deployed soon for you. 👍

**Comment by edin008** [comment]
I had the same issue. Maybe this info will help in future debugging.
My workaround was to cast number format to string so that group by frequency worked correctly,

Example not ok (frequency in number format, group by does not work):
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/e80f391f-fec2-462d-aff8-f993a63ea8a9)
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/82caffa4-2c3a-4163-b079-e88680d0e7de)

Example ok (frequency in string format, group by works)
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/4cdad7fc-b4db-45b7-82b2-e07fede7b6f6)
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/b9143f52-cb60-4305-b600-67585747e715)
