### ISSUE TITLE
Time Series: Missing support for Nanosecond precision

### ISSUE THREAD

**Issue by jirislav** [grafana/clickhouse-datasource#771]
**What happened**:

When I query the time field that includes nanoseconds (e.g. `time DateTime64(9)`), the data points gets cropped (in time) to the nearest millisecond, losing the information of microseconds & nanoseconds. But these data are important to me and I want to visualize the actual series of events how it happened during that one millisecond.

**What you expected to happen**:

To visualize the data points in time as they happened, without cropping the micros & nanos.

**How to reproduce it (as minimally and precisely as possible)**:

Create table:

```
CREATE TABLE nanos (
  time DateTime64(9),
  value UInt32
) ENGINE = MergeTree
  ORDER BY time;
```

Fill it with some nanosecond data throughout 3 milliseconds:

```
INSERT INTO nanos SELECT
  now() + INTERVAL (number * 111111) NANOSECOND,
  number
FROM numbers(30);
```

What we'll get:

```
SELECT *
FROM nanos

┌──────────────────────────time─┬─value─┐
│ 2024-03-22 08:20:20.000000000 │     0 │
│ 2024-03-22 08:20:20.000111111 │     1 │
│ 2024-03-22 08:20:20.000222222 │     2 │
│ 2024-03-22 08:20:20.000333333 │     3 │
│ 2024-03-22 08:20:20.000444444 │     4 │
│ 2024-03-22 08:20:20.000555555 │     5 │
│ 2024-03-22 08:20:20.000666666 │     6 │
│ 2024-03-22 08:20:20.000777777 │     7 │
│ 2024-03-22 08:20:20.000888888 │     8 │
│ 2024-03-22 08:20:20.000999999 │     9 │
│ 2024-03-22 08:20:20.001111110 │    10 │
│ 2024-03-22 08:20:20.001222221 │    11 │
│ 2024-03-22 08:20:20.001333332 │    12 │
│ 2024-03-22 08:20:20.001444443 │    13 │
│ 2024-03-22 08:20:20.001555554 │    14 │
│ 2024-03-22 08:20:20.001666665 │    15 │
│ 2024-03-22 08:20:20.001777776 │    16 │
│ 2024-03-22 08:20:20.001888887 │    17 │
│ 2024-03-22 08:20:20.001999998 │    18 │
│ 2024-03-22 08:20:20.002111109 │    19 │
│ 2024-03-22 08:20:20.002222220 │    20 │
│ 2024-03-22 08:20:20.002333331 │    21 │
│ 2024-03-22 08:20:20.002444442 │    22 │
│ 2024-03-22 08:20:20.002555553 │    23 │
│ 2024-03-22 08:20:20.002666664 │    24 │
│ 2024-03-22 08:20:20.002777775 │    25 │
│ 2024-03-22 08:20:20.002888886 │    26 │
│ 2024-03-22 08:20:20.002999997 │    27 │
│ 2024-03-22 08:20:20.003111108 │    28 │
│ 2024-03-22 08:20:20.003222219 │    29 │
└───────────────────────────────┴───────┘
```

**Screenshots**

![image](https://github.com/grafana/clickhouse-datasource/assets/7583416/400a27e7-3263-43e6-b04c-1d5e019265c6)

**Anything else we need to know?**:

🤷

**Environment**:

- Grafana version: v10.0.2 (but this [should be enough](https://github.com/grafana/grafana/pull/64529))
- Plugin version: Don't know how to find out, but I've just installed it, so it's probably latest
- OS Grafana is installed on: Docker image
- User OS & Browser: Ubuntu 22.04 / Chrome Version 123.0.6312.58 (Official Build) (64-bit)
- Others:

**Comment by SpencerTorres** [comment]
I believe this is a limitation of Grafana. The data is actually returned with nanoseconds to the browser (you can see the `nanos` field in the query inspector), but it will not be displayed on most panels. Internally it gets converted to a JavaScript `Date`, and those are limited to milliseconds. The same goes for the dashboard time range, so you cant even filter time ranges less than 1ms apart.

You might be able to find a workaround by converting the time to Unix nanos, and then instead of using a time chart just use a number chart, but filtering will be difficult. Keep in mind you might also need to scale the number to fit within JavaScript's number limit to prevent rounding issues.

Related discussion on Grafana: https://github.com/grafana/grafana/issues/6252#issuecomment-1566460589

Related discussion on this repo https://github.com/grafana/clickhouse-datasource/discussions/479
